### PR TITLE
ST 146 - Now publishing pytest and coverage HTML and JUnit reports

### PR DESCRIPTION
**Pull request by SKAJohanVenter**
HTML and JUnit versions of the test runs are now published for every build.

E.g for pipeline job [61650980](https://gitlab.com/ska-telescope/lmc-base-classes/pipelines/61650980):

 - The artifacts can be browsed [here](https://gitlab.com/ska-telescope/lmc-base-classes/-/jobs/213693544/artifacts/browse)

The `gitlab.io` published resources (amongst others):
- [JUnit](https://ska-telescope.gitlab.io/-/lmc-base-classes/-/jobs/213693544/artifacts/public/lmcbaseclasses_pytest_junit.xml)
- [Coverage](https://ska-telescope.gitlab.io/-/lmc-base-classes/-/jobs/213693544/artifacts/public/lmcbaseclasses_htmlcoverage/index.html) 
- [Pytest results ](https://ska-telescope.gitlab.io/-/lmc-base-classes/-/jobs/213693544/artifacts/public/lmcbaseclasses_pytest_report.html)

JIRA: ST-146

### CODE REVIEW

**Review by Matteo04052017 — CHANGES_REQUESTED** [review]
Why the report is not visible at the following link? https://ska-telescope.gitlab.io/lmc-base-classes/
An example of correct upload is: https://ska-telescope.gitlab.io/tango-example/

**Comment by SKAJohanVenter** [comment]
The `pages` Gitlab job makes everything in the `public` folder accessable and serves a `index.html`. 
The example you have point to serves the coverage report's `index.html` since it's the `index.html` in the `public` folder.

**But** now we need to serve **more** than just coverage reports, and there can only be one `index.html` that will be served in the `public` directory.

What we ideally should have is our own `index.html` that lives in the `public` directory and that contains links to the various reports we serve.

**Comment by Matteo04052017** [comment]
The problem is that now at that page there is a 404 http error...

**Comment by SKAJohanVenter** [comment]
Yeah, hence the suggestion to add our own `index.html`.
See the GitLab path resolution here: https://docs.gitlab.com/ee/user/project/pages/introduction.html

**Comment by Matteo04052017** [comment]
I think there is only one coverage that we need to show that is this one: https://ska-telescope.gitlab.io/-/lmc-base-classes/-/jobs/213693544/artifacts/public/lmcbaseclasses_htmlcoverage/index.html

The other coverage reports can go in another directory.

**Comment by SKAJohanVenter** [comment]
There is only one coverage report, the other HTML report is the actual `pytest` results. I would argue that the the test results are more useful to display than the coverage if we had to choose one.

By adding a `index.html` with links to both the HTML reports (pytest and coverage) as well as other resources we solve the 404 issue and have easy reference to the reports/files

**Comment by Matteo04052017** [comment]
There are two things important here: the first one is to display something (for me it is just the same if it is the coverage of the tests) and the second one is that the "status.json" has to be accessible in the main page like here: https://ska-telescope.gitlab.io/tango-example/status.json (this is for the dashboard).

For the index, you can choose what you prefer!

**Comment by SKAJohanVenter** [comment]
For future reference:
https://ska-telescope.gitlab.io/-/lmc-base-classes/-/jobs/214258817/artifacts/public/index.html

**Pull request closed without merging**
